### ISSUE TITLE
In future we should have a new custom API parameter for a shorthand pollutant name. I.e CO, NO2, PM2.5

### ISSUE THREAD

**Issue by Daniilmass** [Metatavu/megasense-data-portal-api-spec#137]
Also, for now you could replace the custom shorthand pollutant names with "variableName" parameter available from the API. In future we should have a new custom API parameter for a shorthand name. But for now, "variableName" will do :D (It is something like "cnc_CO_gas")

_Originally posted by @Daniilmass in https://github.com/Metatavu/megasense-go2-app/pull/175#discussion_r1319834262_

**Comment by kaeline** [comment]
@Daniilmass There's _displayName_ field of pollutant, we can also add "_shortDisplayName_".
